-- CONTRACTS 테이블에 DATE, TIME 컬럼 없을 경우 추가.
ALTER TABLE `CONTRACTS` ADD COLUMN `DATE` VARCHAR(8) DEFAULT NULL AFTER `CONTRACT_TIME_ID`;
ALTER TABLE `CONTRACTS` ADD COLUMN `TIME` VARCHAR(2) DEFAULT NULL AFTER `DATE`;
ALTER TABLE `CONTRACTS` ADD COLUMN `APPLY_MSG` VARCHAR(255) DEFAULT NULL AFTER `TIME`;
ALTER TABLE `CONTRACTS` ADD COLUMN `REJECT_MSG` VARCHAR(255) DEFAULT NULL AFTER `APPLY_MSG`;

-- 20170426
ALTER TABLE `USERS` ADD COLUMN `GENDER` VARCHAR(6) DEFAULT NULL AFTER `PASSWORD`;
ALTER TABLE `USERS` ADD COLUMN `IMAGE_URL` VARCHAR(255) DEFAULT NULL AFTER `BIRTH`;
ALTER TABLE `HUMANBOOK` ADD COLUMN `IMAGE_URL` VARCHAR(255) DEFAULT NULL AFTER `STATE`;

-- 20170503
ALTER TABLE CATEGORY ADD COLUMN `PARENT_CATEGORY_ID` INT AFTER `DESC`

-- 20170511
ALTER TABLE `CATEGORY` ADD COLUMN `IMAGE_URL` VARCHAR(255) DEFAULT NULL AFTER `PARENT_CATEGORY_ID`;
